HospitalSystem/Controllers/LoginController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using HospitalSystem.Model;
using HospitalSystem.Backend.Business.Interfaces;
using HospitalSystem.Backend.Utilities;
using Microsoft.Extensions.Options;
using System.Globalization;
using Microsoft.AspNetCore.Hosting;
using System.IO;

namespace HospitalSystem.Controllers
{
    public class LoginController : Controller
    {
        private IBusinessUser _businessUser;
        private readonly AppSettings _appSettings;
        private readonly IHostingEnvironment _env;

        public LoginController(IOptions<AppSettings> appSettings, IBusinessUser businessUser, IHostingEnvironment env)
        {
            _businessUser = businessUser;
            _appSettings = appSettings.Value;
            _env = env;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult GetUserInfo(string username)
        //public async Task<IActionResult> SaveDoctor([FromBody] Doctor request)
        {
            //Verification.
            if (!this.User.Identity.IsAuthenticated)
            {
                // Home Page.  
                return Json(null);
            }

            var result = _businessUser.GetUserInfo(username).Result;

            if (result == null) return Json(null);

            string pathServer = Path.Combine(_env.WebRootPath, "Files", "Doctor");
            result.SFIRSTNAME = (CultureInfo.InvariantCulture.TextInfo.ToTitleCase(result.SFIRSTNAME));
            result.SSECONDNAME = (CultureInfo.InvariantCulture.TextInfo.ToTitleCase(result.SSECONDNAME));
            result.SLASTNAME = (CultureInfo.InvariantCulture.TextInfo.ToTitleCase(result.SLASTNAME));
            result.SLASTNAME1 = (CultureInfo.InvariantCulture.TextInfo.ToTitleCase(result.SLASTNAME1));

            //string fullPathImage = string.Format("{0}{1}", Utils.GetPathDoctor(), result.SPATHIMAGE);
            string fullPathImage = string.Format("{0}/{1}", pathServer, result.SPATHIMAGE);

            if (System.IO.File.Exists(fullPathImage))
            {
                Byte[] bytes = System.IO.File.ReadAllBytes(fullPathImage);
                result.base64image = Convert.ToBase64String(bytes);
            }

            return Json(result);
        }

        [BindProperty]
        public LoginViewModel LoginModel { get; set; }

        [HttpPost]
        public async Task<IActionResult> OnPostLogIn()
        {
            try
            {
                var x = LoginModel;

                if (ModelState.IsValid)
                {

                    var result = _businessUser.Authenticate(LoginModel.Username, LoginModel.Password);

                    if (result.Result.resultado == 0)
                    {
                        // Login In.  
                        await this.SignInUser(LoginModel.Username, true, result.Result.nidprocess);

                       // HttpContext.Session.Set("xxx", Convert.ToByte(resultDoctor.Result));
                        

                        // Info.  
                        return this.RedirectToAction("Index", "Home");
                    }
                    TempData["Message"] = result.Result.mensaje;
                } else TempData["Message"] = "Debe llenar ambos campos";
            }
            catch (Exception ex)
            {
                Console.Write(ex);
            }

            return this.RedirectToAction("Index", "Login");
        }

        private async Task SignInUser(string username, bool isPersistent, int idUser)
        {
            // Initialization.  
            var claims = new List<Claim>();

            try
            {
                // Setting  
                claims.Add(new Claim(ClaimTypes.Name, username));
                claims.Add(new Claim(ClaimTypes.NameIdentifier, idUser.ToString()));
                var claimIdenties = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                var claimPrincipal = new ClaimsPrincipal(claimIdenties);
                var authenticationManager = Request.HttpContext;

                // Sign In.  
                await authenticationManager.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, claimPrincipal, new AuthenticationProperties() { IsPersistent = isPersistent });
            }
            catch (Exception ex)
            {
                // Info  
                throw ex;
            }
        }

        public async Task<IActionResult> LogOff()
        {
            try
            {
                // Setting.  
                var authenticationManager = Request.HttpContext;

                // Sign Out.  
                await authenticationManager.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            }
            catch (Exception ex)
            {
                // Info  
                throw ex;
            }

            // Info.  
            return this.RedirectToAction("Index", "Login");
        }
    }
}

HospitalSystem/Views/Login/Index.cshtml
@{
    Layout = null;
}

@model HospitalSystem.Model.LoginViewModel

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>:: Clínica Lobaton ::</title>
    <link rel="icon" href="favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="~/assets/plugins/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" type="text/css">

    <!-- Custom Css -->
    <link rel="stylesheet" href="~/assets/css/main.css" />

</head>

<body class="theme-cyan authentication">
    <div class="container">
        <div class="card-top"></div>
        <div class="card">
            <h1 class="title"><span>Clínica Lobaton</span>Login</h1>
            <div class="body">
                <form method="post">
                    @Html.AntiForgeryToken()
                    <div class="input-group icon before_span">
                        <span class="input-group-addon"> <i class="zmdi zmdi-account"></i> </span>
                        <div class="form-line">
                            @*<input type="text" class="form-control" name="username" placeholder="Username" required autofocus>*@
                            @Html.TextBoxFor(m => m.Username, new { @class = "form-control", placeholder = "Usuario"})
                            @*@Html.ValidationMessageFor(m => m.Username, "", new { @class = "text-danger" })*@
                        </div>
                    </div><br />
                    <div class="input-group icon before_span">
                        <span class="input-group-addon"> <i class="zmdi zmdi-lock"></i> </span>
                        <div class="form-line">
                            @*<input type="password" class="form-control" name="password" placeholder="Password" required>*@
                            @Html.PasswordFor(m => m.Password, new { @class = "form-control", placeholder = "Contraseña" })
                            @*@Html.ValidationMessageFor(m => m.Password, "", new { @class = "text-danger" })*@
                        </div>
                    </div><br />
                    @if (TempData["Message"] != null)
                    {
                        <div style="text-align: center">
                            <span style="color:red;">@TempData["Message"].ToString()</span>
                        </div><br />
                    }
                    <div>
                        <!--<div class="">-->
                            @*<input type="checkbox" name="rememberme" id="rememberme" class="filled-in chk-col-pink">*@
                            <!--@Html.CheckBoxFor(x => x.isPersistent, new { @class = "filled-in chk-col-pink" })
                            <label for="rememberme">Recuerdame</label>
                        </div>-->
                        <div class="text-center">
                            @*<a formaction="/Login/OnPostLogIn" class="btn btn-raised waves-effect g-bg-cyan">INGRESAR</a>*@
                            @*<a asp-page-handler="LogIn" class="btn btn-raised waves-effect g-bg-cyan">INGRESAR</a>*@
                            <button formaction="/Login/OnPostLogIn" class="btn btn-raised waves-effect g-bg-cyan">INGRESAR</button>
                            @*<input type="submit" value="Submit" />*@
                            @*<a href="sign-up.html" class="btn btn-raised waves-effect">SIGN UP</a>*@
                        </div>
                        <div class="text-center"> @*<a href="forgot-password.html">Forgot Password?</a>*@</div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="theme-bg"></div>

    <!-- Jquery Core Js -->
    @*<script src="~/assets/bundles/libscripts.bundle.js"></script>*@ <!-- Lib Scripts Plugin Js -->
    @*<script src="~/assets/bundles/vendorscripts.bundle.js"></script>*@ <!-- Lib Scripts Plugin Js -->

    @*<script src="~/assets/bundles/mainscripts.bundle.js"></script>*@<!-- Custom Js -->
</body>
</html>